# Generated by Django 2.2.6 on 2019-11-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191104_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='fecha_creacion',
        ),
    ]
